/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoundaryRouteImport } from './routes/boundary'
import { Route as BusRouteImport } from './routes/bus'
import { Route as FerryRouteImport } from './routes/ferry'
import { Route as MtrRouteImport } from './routes/mtr'
import { Route as NewsRouteImport } from './routes/news'
import { Route as WeatherRouteImport } from './routes/weather'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoundaryRoute = BoundaryRouteImport.update({
  id: '/boundary',
  path: '/boundary',
  getParentRoute: () => rootRouteImport,
} as any)
const BusRoute = BusRouteImport.update({
  id: '/bus',
  path: '/bus',
  getParentRoute: () => rootRouteImport,
} as any)
const FerryRoute = FerryRouteImport.update({
  id: '/ferry',
  path: '/ferry',
  getParentRoute: () => rootRouteImport,
} as any)
const MtrRoute = MtrRouteImport.update({
  id: '/mtr',
  path: '/mtr',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boundary': typeof BoundaryRoute
  '/bus': typeof BusRoute
  '/ferry': typeof FerryRoute
  '/mtr': typeof MtrRoute
  '/news': typeof NewsRoute
  '/weather': typeof WeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boundary': typeof BoundaryRoute
  '/bus': typeof BusRoute
  '/ferry': typeof FerryRoute
  '/mtr': typeof MtrRoute
  '/news': typeof NewsRoute
  '/weather': typeof WeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boundary': typeof BoundaryRoute
  '/bus': typeof BusRoute
  '/ferry': typeof FerryRoute
  '/mtr': typeof MtrRoute
  '/news': typeof NewsRoute
  '/weather': typeof WeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/boundary' | '/bus' | '/ferry' | '/mtr' | '/news' | '/weather'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/boundary' | '/bus' | '/ferry' | '/mtr' | '/news' | '/weather'
  id:
    | '__root__'
    | '/'
    | '/boundary'
    | '/bus'
    | '/ferry'
    | '/mtr'
    | '/news'
    | '/weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoundaryRoute: typeof BoundaryRoute
  BusRoute: typeof BusRoute
  FerryRoute: typeof FerryRoute
  MtrRoute: typeof MtrRoute
  NewsRoute: typeof NewsRoute
  WeatherRoute: typeof WeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boundary': {
      id: '/boundary'
      path: '/boundary'
      fullPath: '/boundary'
      preLoaderRoute: typeof BoundaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bus': {
      id: '/bus'
      path: '/bus'
      fullPath: '/bus'
      preLoaderRoute: typeof BusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferry': {
      id: '/ferry'
      path: '/ferry'
      fullPath: '/ferry'
      preLoaderRoute: typeof FerryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mtr': {
      id: '/mtr'
      path: '/mtr'
      fullPath: '/mtr'
      preLoaderRoute: typeof MtrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoundaryRoute: BoundaryRoute,
  BusRoute: BusRoute,
  FerryRoute: FerryRoute,
  MtrRoute: MtrRoute,
  NewsRoute: NewsRoute,
  WeatherRoute: WeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
